name: delete_cache.yml
on:
  pull_request:
    branches:
    - develop
    types:
    - closed

env:
  GH_TOKEN: ${{ github.token }}

# Later, in the jobs section of your actions.yml file.
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        gh cache delete ubuntu-22.04-${{ github.event.pull_request.head.ref }}
